version: '3'
services:

  web:
    build: web
    depends_on:
      - code
      - db
    expose:
      - "80"
    links:
      - db
    volumes:
      - ./code/sqli-labs:/var/www/html
    ports:
      - "8080:80"

  code:
    build: code
    volumes:
      - ./code:/git

  db:
    image: appleshan/mysql-alpine
    expose:
      - "3306"
    ports:
      - "8989:3306"
    environment:
      MYSQL_DATABASE: security
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
